apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hyperdx-config
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        connections.json: |-
          [
            {
              "name": "ClickHouse",
              "host": "http://clickhouse-otel-cluster:8123",
              "port": 8123,
              "username": "hyperdx",
              "password": "{{ .hyperdx }}"
            }
          ]
        sources.json: |
          [
            {
              "from": {
                "databaseName": "otel",
                "tableName": "otel_logs"
              },
              "kind": "log",
              "timestampValueExpression": "TimestampTime",
              "name": "Logs",
              "displayedTimestampValueExpression": "Timestamp",
              "implicitColumnExpression": "Body",
              "serviceNameExpression": "ServiceName",
              "bodyExpression": "Body",
              "eventAttributesExpression": "LogAttributes",
              "resourceAttributesExpression": "ResourceAttributes",
              "defaultTableSelectExpression": "Timestamp,ServiceName,SeverityText,Body",
              "severityTextExpression": "SeverityText",
              "traceIdExpression": "TraceId",
              "spanIdExpression": "SpanId",
              "connection": "Local ClickHouse",
              "traceSourceId": "Traces",
              "sessionSourceId": "Sessions",
              "metricSourceId": "Metrics"
            },
            {
              "from": {
                "databaseName": "otel",
                "tableName": "otel_traces"
              },
              "kind": "trace",
              "timestampValueExpression": "Timestamp",
              "name": "Traces",
              "displayedTimestampValueExpression": "Timestamp",
              "implicitColumnExpression": "SpanName",
              "serviceNameExpression": "ServiceName",
              "bodyExpression": "SpanName",
              "eventAttributesExpression": "SpanAttributes",
              "resourceAttributesExpression": "ResourceAttributes",
              "defaultTableSelectExpression": "Timestamp,ServiceName,StatusCode,round(Duration/1e6),SpanName",
              "traceIdExpression": "TraceId",
              "spanIdExpression": "SpanId",
              "durationExpression": "Duration",
              "durationPrecision": 9,
              "parentSpanIdExpression": "ParentSpanId",
              "spanNameExpression": "SpanName",
              "spanKindExpression": "SpanKind",
              "statusCodeExpression": "StatusCode",
              "statusMessageExpression": "StatusMessage",
              "connection": "Local ClickHouse",
              "logSourceId": "Logs",
              "sessionSourceId": "Sessions",
              "metricSourceId": "Metrics"
            },
            {
              "from": {
                "databaseName": "otel",
                "tableName": "otel_metrics"
              },
              "kind": "metric",
              "timestampValueExpression": "TimeUnix",
              "name": "Metrics",
              "resourceAttributesExpression": "ResourceAttributes",
              "metricTables": {
                "gauge": "otel_metrics_gauge",
                "histogram": "otel_metrics_histogram",
                "sum": "otel_metrics_sum",
                "_id": "682586a8b1f81924e628e808",
                "id": "682586a8b1f81924e628e808"
              },
              "connection": "Local ClickHouse",
              "logSourceId": "Logs",
              "traceSourceId": "Traces",
              "sessionSourceId": "Sessions"
            },
            {
              "from": {
                "databaseName": "otel",
                "tableName": "hyperdx_sessions"
              },
              "kind": "session",
              "timestampValueExpression": "TimestampTime",
              "name": "Sessions",
              "displayedTimestampValueExpression": "Timestamp",
              "implicitColumnExpression": "Body",
              "serviceNameExpression": "ServiceName",
              "bodyExpression": "Body",
              "eventAttributesExpression": "LogAttributes",
              "resourceAttributesExpression": "ResourceAttributes",
              "defaultTableSelectExpression": "Timestamp,ServiceName,SeverityText,Body",
              "severityTextExpression": "SeverityText",
              "traceIdExpression": "TraceId",
              "spanIdExpression": "SpanId",
              "connection": "Local ClickHouse",
              "logSourceId": "Logs",
              "traceSourceId": "Traces",
              "metricSourceId": "Metrics"
            }
          ]
  dataFrom:
    - extract:
        key: clickhouse-basicauth
---

