apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: otel-cluster
spec:
  configuration:
    settings:
      logger/size: "500M"
      logger/count: 1
    clusters:
      - name: otel-cluster
        layout:
          shardsCount: 1
          replicasCount: 1
        templates:
          podTemplate: clickhouse-pod-template
    users:
      collector/password:
        valueFrom:
          secretKeyRef:
            name: clickhouse-passwords
            key: collector
      collector/networks/ip: "::/0"
      collector/grants/query:
        - GRANT SELECT, INSERT, UPDATE, DROP, DELETE, ALTER, CREATE ON otel.*
        - GRANT CREATE DATABASE ON *.*
      grafana/password:
        valueFrom:
          secretKeyRef:
            name: clickhouse-passwords
            key: grafana
      grafana/networks/ip: "::/0"
      grafana/grants/query:
        - GRANT SELECT ON otel.*

      hyperdx/password:
        valueFrom:
          secretKeyRef:
            name: clickhouse-passwords
            key: hyperdx
      hyperdx/networks/ip: "::/0"
      hypderx/grants/query:
        - GRANT SELECT ON otel.*
  defaults:
    templates:
      podTemplate: pod-template
      dataVolumeClaimTemplate: data-volume-template
      logVolumeClaimTemplate: log-volume-template
  templates:
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:latest
              env:
                - name: CLICKHOUSE_ALWAYS_RUN_INITDB_SCRIPTS
                  value: "true"
              volumeMounts:
                - name: bootstrap-configmap-volume
                  mountPath: /docker-entrypoint-initdb.d
          volumes:
            - name: bootstrap-configmap-volume
              configMap:
                name: bootstrap-mounted-configmap
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
      - name: log-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clickhouse-passwords
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: uuid
      rewrite:
        - regexp:
            source: uuid
            target: collector
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: uuid
      rewrite:
        - regexp:
            source: uuid
            target: grafana
    - extract:
        key: clickhouse-basicauth
