apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  mode: daemonset
  config:
    receivers:
      # hostmetrics:
      #   scrapers:
      #     cpu:
      #     disk:
      #     filesystem:
      #     load:
      #     memory:
      #     network:
      #     process:
      #     processes:
      #     paging:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      memory_limiter:
        check_interval: 5s
        limit_mib: 4000
        spike_limit_mib: 500
      batch:
        send_batch_size: 2000
        send_batch_max_size: 2000
        timeout: 5s

    exporters:
      debug:
        verbosity: detailed
      clickhouse:
        endpoint: tcp://clickhouse-otel-cluster:9000?dial_timeout=10s&compress=lz4&async_insert=1
        ttl: 168h # a week
        traces_table_name: otel_traces
        logs_table_name: otel_logs
        create_schema: true
        timeout: 5s
        database: default
        sending_queue:
          queue_size: 1000
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s


    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      pprof:
        endpoint: 0.0.0.0:1777
      zpages:
        endpoint: 0.0.0.0:55679

    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug, clickhouse]
        metrics:
          receivers: [otlp] #[otlp, hostmetrics]
          processors: [memory_limiter, batch]
          exporters: [debug, clickhouse]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug, clickhouse]
