apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: transmission
spec:
  refreshPolicy: CreatedOnce
  target:
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      data:
        username: "{{ .uuid }}"
        password: "{{ .password }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: uuid
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: password
