apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: gitea-sync

configMapGenerator:
- name: scripts
  files:
  - ./mirror.sh

resources:
- deploy.yaml
- secret.yaml
