apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-sync
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: gitea-sync
