apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/enforce: privileged
  name: debug
spec: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug
  namespace: debug
  labels:
    name: debug
spec:
  selector:
    matchLabels:
      name: debug
  template:
    metadata:
      labels:
        name: debug
    spec:
      containers:
        - name: debug
          # image: nixery.dev/shell/nix/tmux/vim
          # command: 
          #   - sleep
          #   - infinity
          image: lscr.io/linuxserver/openssh-server:latest
          env:
            - name: PUBLIC_KEY_URL
              value: https://github.com/zoriya.keys
            - name: SUDO_ACCESS
              value: "true"
            - name: USER_NAME
              value: zoriya
            - name: LISTEN_PORT
              value: "22"
          securityContext:
            privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: debug
  namespace: debug
spec:
  selector:
    name: debug
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
