clusterName: unipop
talosVersion: v1.10.4
kubernetesVersion: 1.33.2
endpoint: https://kube.sdg.moe:6443
allowSchedulingOnMasters: true
cniConfig:
  name: none
patches:
  - |-
    cluster:
      proxy:
        disabled: true
    machine:
      features:
        hostDNS:
          enabled: true
          forwardKubeDNSToHost: false
  - |-
    machine:
      kernel:
        modules:
          - name: zfs
  - |-
    machine:
      kernel:
        modules:
          - name: nvidia
          - name: nvidia_uvm
          - name: nvidia_drm
          - name: nvidia_modeset
      sysctls:
        net.core.bpf_jit_harden: 1
nodes:
  - hostname: kadan
    ipAddress: kube.sdg.moe
    controlPlane: true
    installDisk: /dev/nvme0n1
    certSANs:
      - kube.sdg.moe
    extraManifests:
     - ./patches/disk.yaml
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/zfs
            - siderolabs/nonfree-kmod-nvidia-lts
            - siderolabs/nvidia-container-toolkit-lts
