apiVersion: apps/v1
kind: Deployment
metadata:
  name: yt-dlp
spec:
  template:
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: ytdlp
        image: nixery.dev/shell/yt-dlp
        workingDir: /work
        command: [/app/ytdlp-sync.sh]
        env:
        - name: OUT
          value: /musics
        - name: URL
          valueFrom:
            secretKeyRef:
              name: ytdlp
              key: url
        volumeMounts:
        - name: scripts
          mountPath: /app
          readOnly: true
        - name: cookies
          mountPath: /app/secrets
        - name: work
          mountPath: /work
        - name: musics
          mountPath: /musics
      volumes:
      - name: scripts
        configMap:
          name: sync-scripts
          defaultMode: 0555
      - name: musics
        persistentVolumeClaim:
          claimName: musics
      - name: work
        emptyDir: {}
      - name: cookies
        secret:
          secretName: ytdlp
