apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
spec:
  template:
    spec:
      containers:
        - name: transmission
          image: ghcr.io/home-operations/transmission@4.0.6
          env:
            - TRANSMISSION__UMASK: "002"
            - TRANSMISSION__INCOMPLETE-DIR-ENABLED: false
            - TRANSMISSION__DOWNLOAD-DIR: "/medias/downloads"
            - TRANSMISSION__DOWNLOAD-QUEUE-ENABLED: false
            - TRANSMISSION__RENAME-PARTIAL-FILES: false
            - TRANSMISSION__TRASH-CAN-ENABLED: false
            - TRANSMISSION__SCRIPT-TORRENT-ADDED-ENABLED: true
            - TRANSMISSION__SCRIPT-TORRENT-ADDED-FILENAME: "scripts/guesspath"
          volumeMounts:
            - name: medias
              mountPath: /medias
      volumes:
        - name: medias
