apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flood-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
