apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-downloads
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Ti
  csi:
    driver: zfs.csi.openebs.io
    fsType: zfs
    volumeAttributes:
      openebs.io/poolname: ocean
    volumeHandle: "downloads"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
spec:
  storageClassName: ""
  volumeName: transmission-downloads
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
