apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-medias
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Ti
  csi:
    driver: zfs.csi.openebs.io
    fsType: zfs
    volumeAttributes:
      openebs.io/poolname: ocean
    volumeHandle: "medias"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: medias
spec:
  storageClassName: ""
  volumeName: transmission-medias
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Ti
