apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfs-tank
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
allowVolumeExpansion: true
parameters:
  recordsize: 128k
  compression: "off"
  dedup: "off"
  fstype: zfs
  poolname: tank
provisioner: zfs.csi.openebs.io
