apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-cluster
spec:
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.5-0.3.0
  instances: 1
  storage:
    size: 4Gi

  postgresql:
    shared_preload_libraries:
    - "vchord.so"
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich
spec:
  name: immich
  owner: immich
  cluster:
    name: immich-cluster
  extensions:
  - name: vector
    ensure: present
  - name: vchord
    ensure: present
  - name: earthdistance
    ensure: present
