apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-pictures
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Ti
  csi:
    driver: zfs.csi.openebs.io
    fsType: zfs
    volumeAttributes:
      openebs.io/poolname: ocean
    volumeHandle: "pictures"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pictures
spec:
  storageClassName: ""
  volumeName: immich-pictures
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Ti

