apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      apps.kubernetes.io/name: proxy

resources:
  - ./deploy.yaml
  - ./svc.yaml
  - ./ingress.yaml
