apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-ca
  namespace: postgres
spec:
  isCA: true
  commonName: postgres-ca
  secretName: postgres-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: postgres-ca
  namespace: postgres
spec:
  ca:
    secretName: postgres-ca
