apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-ca
  namespace: postgres
spec:
  isCA: true
  commonName: postgres-ca
  secretName: postgres-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: postgres-ca
  namespace: postgres
spec:
  ca:
    secretName: postgres-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-replication-cert
  namespace: postgres
spec:
  secretName: postgres-replication-cert
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  usages:
    - server auth
  dnsNames:
   - postgres-cluster-rw
   - postgres-cluster-rw.postgres
   - postgres-cluster-rw.postgres.svc
   - postgres-cluster-r
   - postgres-cluster-r.postgres
   - postgres-cluster-r.postgres.svc
   - postgres-cluster-ro
   - postgres-cluster-ro.postgres
   - postgres-cluster-ro.postgres.svc
  issuerRef:
    name: postgres-ca
    kind: Issuer
    group: cert-manager.io
