apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-server-cert
  namespace: postgres
spec:
  secretName: postgres-server-cert
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  usages:
    - server auth
  dnsNames:
   - postgres-cluster-rw
   - postgres-cluster-rw.postgres
   - postgres-cluster-rw.postgres.svc
   - postgres-cluster-r
   - postgres-cluster-r.postgres
   - postgres-cluster-r.postgres.svc
   - postgres-cluster-ro
   - postgres-cluster-ro.postgres
   - postgres-cluster-ro.postgres.svc
  issuerRef:
    name: postgres-ca
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-replication-cert
spec:
  secretName: postgres-replication-cert
  usages:
    - client auth
  commonName: streaming_replica
  issuerRef:
    name: postgres-ca
    kind: Issuer
    group: cert-manager.io
