apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-ca
  namespace: postgres
spec:
  isCA: true
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  commonName: postgres-ca
  secretName: postgres-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: postgres-ca
  namespace: postgres
spec:
  ca:
    secretName: postgres-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-replication-cert
  namespace: postgres
spec:
  secretName: postgres-replication-cert
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  usages:
    - client auth
  commonName: streaming_replica
  issuerRef:
    name: postgres-ca
    kind: Issuer
    group: cert-manager.io
