apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: meelo-db
  namespace: postgres
spec:
  name: meelo
  owner: meelo
  cluster:
    name: postgres-cluster
  databaseReclaimPolicy: delete
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-meelo
spec:
  secretName: postgres-meelo
  usages:
  - client auth
  # same as pg user
  commonName: meelo
  keystores:
    pkcs12:
      create: true
      password: meelo
      profile: Modern2023
  issuerRef:
    name: postgres-ca
    kind: ClusterIssuer
    group: cert-manager.io
