apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: meilisearch
  template:
    metadata:
      labels:
        app.kubernetes.io/component: meilisearch
    spec:
      containers:
      - name: meilisearch
        image: getmeili/meilisearch:v1.53
        ports:
        - name: http
          containerPort: 7700
        env:
        - name: MEILI_ENV
          value: production
        - name: MEILI_LOG_LEVEL
          value: WARN
        - name: MEILI_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: meilisearch
              key: uuid
        volumeMounts:
        - name: data
          mountPath: /meili_data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: meilisearch
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: meilisearch
  ports:
  - name: http
    port: 7700
    targetPort: http
