apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-key
spec:
  refreshPolicy: CreatedOnce
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: uuid
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jwt
spec:
  refreshPolicy: CreatedOnce
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: uuid
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: meilisearch
spec:
  refreshPolicy: CreatedOnce
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: uuid
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq
spec:
  refreshPolicy: CreatedOnce
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: uuid
