apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://github.com/argoproj/argo-helm
    targetRevision: argo-cd-8.1.2
    path: charts/argo-cd
    helm:
      values: |
        global:
          domain: argocd.sdg.moe
        certificate:
          enabled: true
        server:
          ingress:
            enabled: true
            ingressClassName: cilium
            annotations:
              ingress.cilium.io/tls-passthrough: "true"
              ingress.cilium.io/force-https: "true"
              cert-manager.io/cluster-issuer: letsencrypt
            hostname: argocd.sdg.moe
            tls: true
