apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse-operator
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    # i don't wanna deal with making this cluster scoped
    namespace: otel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    # needed because the CRDs are too long for kubectl apply
    - ServerSideApply=true
  source:
    repoURL: https://helm.altinity.com
    chart: altinity-clickhouse-operator
    targetRevision: 0.25.5
    helm:
      valuesObject:
        rbac:
          namespaceScoped: true
