apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      syncOptions:
        - CreateNamespace=true
      managedNamespaceMetadata:
        labels:
          pod-security.kubernetes.io/enforce: privileged
  source:
    repoURL: https://openebs.github.io/openebs
    chart: openebs
    targetRevision: v4.3.2
    helm:
      valuesObject:
        engines:
          local:
            lvm:
              enabled: false
          replicated:
            mayastor:
              enabled: false
        alloy:
          enabled: false
        loki:
          enabled: false

        zfs-localpv:
          zfsNode:
            encrKeysDir: /var/openebs/keys
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfs-tank
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  recordsize: 128k
  compression: "off"
  dedup: "off"
  fstype: zfs
  poolname: tank
provisioner: zfs.csi.openebs.io
