apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      syncOption:
        - CreateNamespace=true
  source:
    repoURL: https://github.com/zoriya/snow
    targetRevision: HEAD
    path: apps/postgres
