kind: Namespace
apiVersion: v1
metadata:
  name: cnpg
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # needed because the CRDs are too long for kubectl apply
    syncOptions:
    - ServerSideApply=true
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: v0.24.0
    helm:
      valuesObject: {}
---
kind: Namespace
apiVersion: v1
metadata:
  name: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: postgres
spec:
  instances: 3

  storage:
    size: 10Gi

  # this is here because no `Role` crd exsists yet.
  # see https://github.com/cloudnative-pg/cloudnative-pg/issues/5341
  managed:
    roles:
    - name: authentik
      login: true
      disablePassword: true
