apiVersion: v1
kind: PersistentVolume
metadata:
  name: meelo-musics
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Ti
  csi:
    driver: zfs.csi.openebs.io
    fsType: zfs
    volumeAttributes:
      openebs.io/poolname: ocean
    volumeHandle: "musics"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: musics
spec:
  storageClassName: ""
  volumeName: meelo-musics
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Ti
