apiVersion: apps/v1
kind: Deployment
metadata:
  name: flood
spec:
  template:
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: flood
        image: jesec/flood:4.10.0
        env:
        - name: HOME
          value: /config
        - name: FLOOD_OPTION_AUTH
          value: none
        - name: FLOOD_OPTION_TRURL
          value: "http://transmission:9091/transmission/rpc"
        - name: FLOOD_OPTION_TRUSER
          valueFrom:
            secretKeyRef:
              name: transmission
              key: username
        - name: FLOOD_OPTION_TRPASS
          valueFrom:
            secretKeyRef:
              name: transmission
              key: password
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
          readOnly: true
        - name: medias
          mountPath: /medias
          readOnly: true
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: flood-config
      - name: medias
        persistentVolumeClaim:
          claimName: medias
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads
