apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smartrss
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: url
    remoteRef:
      key: smartrss-url
